version: "3.8"
services:
    app:
        build: .
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - mariadb
        environment:
            - MYSQL_HOST=mariadb
            - MYSQL_PORT=3306
    mariadb:
        image: mariadb:10.4
        restart: always
        ports:
            - 3306:3306
        environment:
            - MARIADB_DATABASE=resourcesManager
            - MARIADB_ROOT_PASSWORD=root
        volumes:
            - resources_management_volume:/var/lib/mysql
volumes:
    resources_management_volume:
