export enum RoleType {
  ROLE_USER = "ROLE_USER",
  ROLE_RESPONSABLE = "ROLE_RESPONSABLE",
  ROLE_TECHNICIEN = "ROLE_TECHNICIEN",
  ROLE_CHEF_DEPARTEMENT = "ROLE_CHEF_DEPARTEMENT",
  ROLE_ENSEIGNANT = "ROLE_ENSEIGNANT",
  ROLE_FOURNISSEUR = "ROLE_FOURNISSEUR"
}
